name: Main

on:
  workflow_dispatch:

env:
  PROJECT_NAME: Silence-Engine

jobs:
  get-commit-hash:
    name: Get Commit Hash
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.get_hash.outputs.commit_hash }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Short Commit Hash
        id: get_hash
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

  Build:
    name: ${{ matrix.name }}
    needs: get-commit-hash
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            os: windows-2022
            buildArgs: "windows -release -final -D officialBuild"
            setupCommand: '.\setup\windows.bat'
            artifactName: windowsBuild-x86_64
            artifactPath: 'export\release\windows\bin\*'

          - name: Linux
            os: ubuntu-22.04
            buildArgs: "linux -release -final -D officialBuild"
            setupCommand: sh ./setup/unix.sh
            artifactName: linuxBuild-x86_64
            artifactPath: export/release/linux/bin/*

          - name: macOS x86_64
            os: macos-13
            setupCommand: sh ./setup/unix.sh
            buildArgs: "mac -64 -D HXCPP_M64 -release -final -D officialBuild"
            artifactName: macOSBuild-x86_64
            artifactPath: export/release/macos/bin/*

          - name: macOS ARM64
            os: macos-14
            setupCommand: sh ./setup/unix.sh
            buildArgs: "mac -arm64 -D HXCPP_ARM64 -release -final -D officialBuild"
            artifactName: macOSBuild-arm64
            artifactPath: export/release/macos/bin/*

          - name: Android
            os: ubuntu-latest
            buildArgs: "android -release -final -D officialBuild"
            setupCommand: sh ./setup/unix.sh
            artifactName: androidBuild
            artifactPath: "export/release/android/**/*.apk"

          - name: iOS
            os: macos-13
            buildArgs: "ios -release -final -nosign -D officialBuild"
            setupCommand: sh ./setup/unix.sh
            artifactName: iOSBuild
            artifactPath: "export/release/ios/build/Release-iphoneos/*.ipa"

    uses: ./.github/workflows/build.yml
    with:
      name: ${{ matrix.name }}
      os: ${{ matrix.os }}
      buildArgs: ${{ matrix.buildArgs }}
      setupCommand: ${{ matrix.setupCommand }}
      artifactName: ${{ matrix.artifactName }}
      artifactPath: ${{ matrix.artifactPath }}

  Releaser:
    name: Releaser
    needs: [get-commit-hash, Build]
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Download Windows Build
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: windowsBuild-x86_64
          path: /home/runner/artifacts/windows

      - name: Download Linux Build
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: linuxBuild-x86_64
          path: /home/runner/artifacts/linux

      - name: Download macOS x86_64 Build
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: macOSBuild-x86_64
          path: /home/runner/artifacts/macos-x86_64

      - name: Download macOS ARM64 Build
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: macOSBuild-arm64
          path: /home/runner/artifacts/macos-arm64

      - name: Download Android Build
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: androidBuild
          path: /home/runner/artifacts/android

      - name: Download iOS Build
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: iOSBuild
          path: /home/runner/artifacts/ios

      - name: Prepare Release Files
        run: |
          mkdir -p /home/runner/release_files

          if [ -d "/home/runner/artifacts/windows" ]; then
            zip -r /home/runner/release_files/${{ env.PROJECT_NAME }}-Windows-x86_64.zip /home/runner/artifacts/windows
          fi

          if [ -d "/home/runner/artifacts/linux" ]; then
            zip -r /home/runner/release_files/${{ env.PROJECT_NAME }}-Linux-x86_64.zip /home/runner/artifacts/linux
          fi

          if [ -d "/home/runner/artifacts/macos-x86_64" ]; then
            zip -r /home/runner/release_files/${{ env.PROJECT_NAME }}-MacOS-x86_64.zip /home/runner/artifacts/macos-x86_64
          fi

          if [ -d "/home/runner/artifacts/macos-arm64" ]; then
            zip -r /home/runner/release_files/${{ env.PROJECT_NAME }}-MacOS-arm64.zip /home/runner/artifacts/macos-arm64
          fi

          if [ -d "/home/runner/artifacts/android" ]; then
            mv /home/runner/artifacts/android/*.apk /home/runner/release_files/${{ env.PROJECT_NAME }}-Android.apk 2>/dev/null || true
          fi

          if [ -d "/home/runner/artifacts/ios" ]; then
            mv /home/runner/artifacts/ios/*.ipa /home/runner/release_files/${{ env.PROJECT_NAME }}-IOS.ipa 2>/dev/null || true
          fi

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          name: "DevBuild ${{ needs.get-commit-hash.outputs.commit_hash }}"
          tag_name: "devbuild-${{ needs.get-commit-hash.outputs.commit_hash }}"
          prerelease: true
          files: |
            /home/runner/release_files/*
